spring.application.name: employee-api
server.port: 8111
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping=TRACE: